#!/usr/bin/env bash
#
# Checks built binary
#

# FIXME(konishchev): Remove -x
set -eux

if [ $# -ne 1 ]; then
    echo "Usage: $0 TARGET" >&2
    exit 1
fi

target="$1"
[ "$(uname)" = Linux ] || exit 0

# FIXME(konishchev): Implement
ldd "target/${CARGO_BUILD_TARGET:-}/$target/binup"