name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: '0 19 * * 5'
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ format('{0}-latest', matrix.os) }}

    strategy:
      matrix:
        os: [ubuntu, macos]

    steps:
    - uses: actions/checkout@v4

    - name: Drop caches
      run: rm Cargo.lock

    - name: Build
      run: cargo build

    - name: Test
      run: cargo test