name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: '0 19 * * 5'
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    # name: Test on ${{ matrix.os }}
    # runs-on: ${{ format('{0}-latest', matrix.os) }}
    name: Test on ${{ matrix.config.os }}
    runs-on: ${{ format('{0}-latest', matrix.config.os) }}

    strategy:
      matrix:
        # os: [ubuntu, macos]
        config:
          - os: ubuntu
            env:
              TEST: VALUE
          - os: macos
            env: {}

    steps:
    - uses: actions/checkout@v4

    - name: Test env
      run: env
      env: ${{ matrix.config.env }}

    - name: Drop caches
      run: rm Cargo.lock

    - name: Build
      run: cargo build

    - name: Test
      run: ./test
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}